<a href="https://colab.research.google.com/github/Bikramjit08/MACHINE_LEARNING/blob/main/data_processing_flats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import numpy as np
import pandas as pd

In [113]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [114]:
df= pd.read_csv('flats.csv')
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [115]:
# shape
df.shape

(3028, 20)

In [116]:
#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.2+ KB

In [117]:
# check for missing value
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [118]:
df.drop(columns=['link','property_id'],inplace=True)

In [119]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [120]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# SOCIETY **COLUMN** ⚛

In [121]:
# society
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
Signature Global Solera3.7 ★                         28
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Bestech Park View Residency3.9 ★                     23
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Supertech Araville                                   19
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 16
M3M Merlin3.7 ★                                      16
Godrej Oasis3.9 ★                                    16
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
MVN Athens3.7 ★                                      14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Ramsons Kshitij3.7 ★                                 14
Orchid Petals4.1 ★                                   14
Vatika The Seven Lamps3.8 ★                          14
Umang Winter Hills3.9 ★                              14
DLF The Primus3.9 ★                                  14
Imperia The Esfera                                   14
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Godrej Aria3.8 ★                                     11
DLF The Skycourt4.2 ★                                11
M3M Soulitude                                        11
TARC Maceo3.8 ★                                      11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Breez Global Hill View                               11
SBTL Caladium                                        11
Pyramid Urban Homes 2                                10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Breez Global Heights4.2 ★                            10
Ramprastha The Edge Towers3.5 ★                      10
Capital Residences 360                               10
Puri Diplomatic Greens4.0 ★                          10
Signature Global Synera3.4 ★                         10
ATS Kocoon                                           10
DLF New Town Heights 24.0 ★                          10
ILD Greens4.1 ★                                      10
Godrej Air                                           10
Pivotal Devaan                                       10
Pareena Mi Casa                                       9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
M3M Skycity                                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Assotech Blith                                        8
Birla Navya                                           8
GLS Avenue 51                                         8
M3M Capital                                           8
Vatika Lifestyle Homes3.8 ★                           8
Orris Aster Court Premier                             8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
Emaar Digihomes                                       8
The Lions CGHS                                        8
Signature Andour Heights3.8 ★                         7
AIPL Zen Residences                                   7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Ansal Housing Highland Park                           7
Emaar Imperial Gardens3.8 ★                           7
Trisara Our Homes 3                                   7
Mapsko Casa Bella3.8 ★                                7
Greenopolis                                           6
HSIIDC Sidco Aravali                                  6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Hero Homes                                            6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Shapoorji Pallonji Joyville Gurugram                  6
Kiran Residency                                       6
Pyramid Urban                                         6
BPTP Astaire Gardens3.7 ★                             6
Supertech Hues                                        6
Signature Global City 63A                             6
DLF Regency Park 13.6 ★                               6
Signature The Roselia3.6 ★                            6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Ashiana Mulberry                                      6
M3M Sierra 68                                         6
Signature Global Grand IVA3.9 ★                       5
Ireo Uptown4.1 ★                                      5
Krisumi Waterfall Residences                          5
Pareena Laxmi Apartments3.6 ★                         5
Conscient Elevate                                     5
Central Park Resorts4.4 ★                             5
Central Park Flower Valley Aqua Front Towers          5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Satya The Hermitage3.5 ★                              5
Apna Enclave                                          5
Godrej Habitat                                        5
Vatika City Homes3.9 ★                                5
Signature Global the Millennia                        5
DLF Park Place4.1 ★                                   5
DLF Regency Park 24.0 ★                               5
Signature Global City 37D Ph 2                        5
Green Court3.7 ★                                      5
Essel Towers                                          5
Silverglades The Melia                                5
Vatika Sovereign Park                                 5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Adani Brahma Samsara Vilasa                           5
Signature Global City 81                              5
Emaar MGF Emerald Estate3.8 ★                         5
ATS Marigold                                          5
Ashiana Anmol3.5 ★                                    5
Krrish Provence Estate                                4
Orris Aster Court                                     4
Signature The Serenas                                 4
Emaar Palm Heights                                    4
Godrej Icon                                           4
Global Hill View                                      4
ILD Grand                                             4
Corona Gracieux                                       4
Unitech Vistas                                        4
DLF New Town Heights3.7 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Unitech Fresco3.8 ★                                   4
Sare Petioles                                         4
Tata Gurgaon Gateway3.8 ★                             4
Railway Officers RPF Society                          4
Lotus Homz4.0 ★                                       4
Godrej Frontier3.7 ★                                  4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Ramprastha Primera                                    4
Ramprastha Skyz                                       4
Prime Habitat                                         4
Maxworth City Residences                              3
Sidhartha NCR One                                     3
Unitech The Residences3.7 ★                           3
Deepak Minda                                          3
Tulip Purple                                          3
Raheja Atharva3.6 ★                                   3
Vatika Independent Floors3.8 ★                        3
Raheja Sampada                                        3
Unitech Uniworld Gardens3.8 ★                         3
Chintels Paradiso3.9 ★                                3
Puri Diplomatic Greens3.9 ★                           3
DLF Royalton Tower                                    3
Sidhartha NCR Greens4.3 ★                             3
Siddhartha Apartment                                  3
The Roselia 2                                         3
Kendriya Vihar4.1 ★                                   3
Valley View Estate                                    3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Guru Gram Haryana CGHS4.1 ★                           3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Vatika Xpressions                                     3
Apex Our Homes                                        3
Shree Arihant Apartment                               3
Dhoot Time Residency4.0 ★                             3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Sare Green Parc                                       3
Adani Aangan Arcade                                   3
AFNHB Jalvayu Vihar3.7 ★                              3
Sunischit Apartments                                  3
ATS Kocoon4.2 ★                                       3
Raheja Revanta                                        3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Bestech Park View City 23.9 ★                         3
Spaze Privvy The Address3.9 ★                         3
Piedmont Taksila heights3.6 ★                         3
Paras Quartier                                        3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
My Home                                               3
Tulip White3.5 ★                                      3
Essel Tower                                           3
DLF Carlton Estate4.0 ★                               3
Smriti Apartment                                      3
Brisk Lumbini Terrace Homes                           3
SS Almeria                                            3
Sukhshanti Apartment                                  3
Unitech Heritage City                                 3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Ambience Lagoon3.9 ★                                  3
Krrish Florence Estate                                3
DLF The Grove                                         3
Sapphire Eighty Three                                 3
Pyramid Elite                                         3
ROF Aalayas3.8 ★                                      2
Park Royal Apartment                                  2
BPTP Mansions Park Prime                              2
BPTP Pedestal                                         2
Sahara Grace                                          2
M3M Sky Lofts                                         2
Godrej Nature Plus Serenity                           2
DLF The Icon3.7 ★                                     2
Tulip Leaf                                            2
Emaar MGF The Enclave                                 2
Housing Board Colony                                  2
Mapsko Paradise3.9 ★                                  2
Professors Enclave CGHS                               2
Vipul Belmonte3.9 ★                                   2
Sidhivinayak Apartments                               2
Ardee City3.8 ★                                       2
Suncity Avenue 76                                     2
MRG World Ultimus                                     2
Samaspurkunj                                          2
HCBS Sports Ville                                     2
Paras Irene3.7 ★                                      2
Adani Aangan Galleria                                 2
Suncity Avenue 1023.9 ★                               2
Suncity Heights3.7 ★                                  2
DLF The Belaire3.9 ★                                  2
Ansal API Esencia3.7 ★                                2
Suposhaa Smartworld Orchard                           2
Raheja Atlantis3.8 ★                                  2
Palam Vihar Society                                   2
Ramprastha The Atrium3.4 ★                            2
Uphar lakshya homes                                   2
Mittal Surya Vihar                                    2
AWHO Shanti Vihar4.0 ★                                2
Vatika INXT Floors                                    2
Today Callidora                                       2
Ashiana Anmol                                         2
BPTP Amstoria3.8 ★                                    2
ss residency                                          2
Raheja Vanya                                          2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Chanderlok Society                                    2
Tulsiani Easy in Homes                                2
Ansal Heights3.2 ★                                    2
Residency Grand                                       2
Ramprastha City                                       2
Tulip Violet                                          2
Emaar MGF Palm Studios                                2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
Apartment                                             2
Vipul World Floors                                    2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Puri The Aravallis                                    2
Silverglades Hightown Residences                      2
BPTP Freedom Park Life4.0 ★                           2
Vatika Emilia Floors3.7 ★                             2
M3M Latitude                                          2
Milan CGHS 9                                          2
Pioneer Urban Presidia                                2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Element One Service                                   2
Oriental Valley CHS                                   2
Elan The Presidential                                 2
Viridian The Plaza 106                                2
The Close South3.9 ★                                  2
Breeze Global Heights                                 2
lagoon apartment                                      2
Supertech Hill Town                                   2
Aqua Front Towers                                     2
Lavanya Apartments                                    2
Ganga Apartment                                       2
Bhagwati Sadan                                        2
Signature Global The Millennia 3                      2
Supertech Hilltown                                    2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
om appartments                                        2
Ambience Caitriona                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Godrej Aria , sector 79 , Gurgaon                     2
Surendra Avenue 69                                    2
Bestech Park View Sanskruti4.1 ★                      2
DLF The Crest3.6 ★                                    2
M3M Ikonic                                            2
Bestech Spa Signature                                 2
Maruti Vihar                                          2
Vasant Appartments                                    2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
ShreeRam Apartment II                                 1

In [122]:
df['society'].value_counts().shape

(639,)

In [123]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [124]:
df['society'].value_counts().shape

(605,)

In [125]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world gems                                 32
emaar mgf emerald floors premier                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
m3m woodshire                                    30
dlf regal gardens                                30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
emaar gurgaon greens                             25
bptp terra                                       25
experion the heartsong                           24
vatika gurgaon                                   24
eldeco accolade                                  24
bestech park view residency                      23
m3m heights                                      22
tata primanti                                    22
ats triumph                                      22
emaar palm gardens                               22
sare crescent parc                               21
godrej                                           21
rof ananda                                       21
experion windchants                              20
antriksh heights                                 19
supertech araville                               19
sare homes                                       19
indiabulls centrum park                          18
ats tourmaline                                   18
m3m skywalk                                      18
m3m golfestate                                   18
mapsko mount ville                               18
chd avenue                                       18
ambience creacions                               18
sobha city                                       18
hcbs sports ville                                18
gls arawali homes                                17
conscient heritage max                           17
pareena coban residences                         17
godrej summit                                    17
m3m merlin                                       16
godrej oasis                                     16
umang monsoon breeze                             16
bestech park view grand spa                      16
dlf the skycourt                                 15
ansal heights 86                                 15
corona optus                                     15
ramsons kshitij                                  15
emaar mgf the palm drive                         15
indiabulls enigma                                14
bestech park view ananda                         14
the close north                                  14
ireo victory valley                              14
orchid petals                                    14
vatika the seven lamps                           14
umang winter hills                               14
dlf the primus                                   14
mvn athens                                       14
ireo skyon                                       14
imperia the esfera                               14
ats kocoon                                       13
ireo the corridors                               13
central park flower valley                       13
puri diplomatic greens                           13
puri emerald bay                                 13
godrej aria                                      11
tarc maceo                                       11
raheja vedaanta                                  11
breez global heights                             11
dlf regency park                                 11
m3m soulitude                                    11
sbtl caladium                                    11
ild greens                                       11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
adani m2k oyster grande                          11
breez global hill view                           11
pivotal devaan                                   10
godrej air                                       10
capital residences 360                           10
ramprastha the edge towers                       10
zara aavaas                                      10
emaar mgf palm hills                             10
signature global synera                          10
pyramid urban homes 2                            10
parsvnath green ville                             9
microtek greenburg                                9
vatika city                                       9
aipl the peaceful homes                           9
pareena mi casa                                   9
bestech park view city                            9
assotech blith                                    8
m3m capital                                       8
vatika lifestyle homes                            8
emaar digihomes                                   8
tulip ivory                                       8
ss                                                8
avl 36 gurgaon                                    8
gls avenue 51                                     8
the lions cghs                                    8
birla navya                                       8
orris aster court premier                         8
m3m skycity                                       8
bestech altura                                    8
sare crescent parc royal greens phase 1           7
vipul lavanya                                     7
signature global city                             7
orris carnation residency                         7
signature global orchard avenue                   7
aipl zen residences                               7
mapsko casa bella                                 7
sare green parc phase 3                           7
ansal housing highland park                       7
emaar imperial gardens                            7
ireo the grand arch                               7
ashiana anmol                                     7
sidhartha ncr one phase                           7
trisara our homes 3                               7
signature andour heights                          7
green court                                       6
hero homes                                        6
signature global park 4                           6
signature global city 63a                         6
hsiidc sidco aravali                              6
signature the roselia                             6
mapsko royale ville                               6
suncity vatsal valley                             6
bptp astaire gardens                              6
ashiana mulberry                                  6
kiran residency                                   6
supertech hues                                    6
bestech park view spa next                        6
greenopolis                                       6
parsvnath exotica                                 6
pyramid urban                                     6
m3m sierra 68                                     6
pioneer araya                                     6
vatika sovereign park                             5
signature global city 37d ph 2                    5
tulip monsella                                    5
m3m the marina                                    5
signature global city 81                          5
central park flower valley aqua front towers      5
essel towers                                      5
unitech uniworld gardens                          5
adani brahma samsara vilasa                       5
satya the hermitage                               5
central park resorts                              5
emaar mgf emerald estate                          5
pareena laxmi apartments                          5
signature global city 92                          5
signature global grand iva                        5
apna enclave                                      5
vatika city homes                                 5
unitech fresco                                    5
dlf park place                                    5
pioneer park                                      5
ireo uptown                                       5
silverglades the melia                            5
godrej habitat                                    5
krisumi waterfall residences                      5
conscient elevate                                 5
ats marigold                                      5
signature global the millennia                    5
krrish provence estate                            4
railway officers rpf society                      4
raheja navodaya                                   4
afnhb jalvayu vihar                               4
signature the serenas                             4
ramprastha skyz                                   4
dlf the arbour                                    4
corona gracieux                                   4
emaar palm heights                                4
orris aster court                                 4
lotus homz                                        4
godrej icon                                       4
sare petioles                                     4
essel tower                                       4
kendriya vihar                                    4
prime habitat                                     4
tata gurgaon gateway                              4
hsiidc sidco shivalik apartments                  4
godrej frontier                                   4
ramprastha primera                                4
global hill view                                  4
ss the coralwood                                  4
ild grand                                         4
unitech vistas                                    4
valley view estate                                3
vatika xpressions                                 3
adani aangan arcade                               3
shri ram apartments                               3
raheja atharva                                    3
satya element one                                 3
spaze privy                                       3
jammu and kashmir bank employees cghs             3
tulip white                                       3
bhagwati sadan                                    3
tulip lemon                                       3
dlf express greens                                3
sare green parc 2                                 3
sidhartha ncr one                                 3
unitech sunbreeze                                 3
sare green parc                                   3
conscient habitat                                 3
chintels paradiso                                 3
vatika independent floors                         3
sidhartha ncr greens                              3
dhoot time residency                              3
piedmont taksila heights                          3
whiteland blissville                              3
sunischit apartments                              3
maxworth city residences                          3
signature global solera 2                         3
tulip purple                                      3
deepak minda                                      3
krrish florence estate                            3
spaze privvy the address                          3
unitech the residences                            3
raheja revanta                                    3
ambience lagoon                                   3
dlf royalton tower                                3
ss residency                                      3
the roselia 2                                     3
dlf carlton estate                                3
dlf the grove                                     3
guru gram haryana cghs                            3
smriti apartment                                  3
tulip petals                                      3
apex our homes                                    3
dlf belvedere towers                              3
shri banke bihari society                         3
paras quartier                                    3
aipl club residences                              3
pivotal riddhi siddhi                             3
pyramid elite                                     3
brisk lumbini terrace homes                       3
sapphire eighty three                             3
my home                                           3
spaze privy at                                    3
ss almeria                                        3
suncity platinum towers                           3
mahindra aura                                     3
shree arihant apartment                           3
sukhshanti apartment                              3
unitech heritage city                             3
raheja sampada                                    3
siddhartha apartment                              3
mapsko paradise                                   2
bptp mansions park prime                          2
orchid island                                     2
aqua front towers                                 2
m3m sky lofts                                     2
ramprastha the atrium                             2
tulip orange                                      2
signature global the millennia 3                  2
residency grand                                   2
dlf the icon                                      2
professors enclave cghs                           2
surendra avenue 69                                2
chanderlok society                                2
emaar mgf palm studios                            2
godrej aria , sector 79 , gurgaon                 2
tulsiani easy in homes                            2
vipul belmonte                                    2
emaar mgf the enclave                             2
adani aangan galleria                             2
uphar lakshya homes                               2
bptp amstoria                                     2
suncity avenue                                    2
dlf the belaire                                   2
park royal apartment                              2
the penthouses at the hibiscus                    2
ss hibiscus                                       2
ganga apartment                                   2
sidhivinayak apartments                           2
viridian the plaza 106                            2
tulip leaf                                        2
vatika emilia floors                              2
samaspurkunj                                      2
oriental valley chs                               2
ardee city                                        2
supertech hilltown                                2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
emaar mgf emerald floors                          2
paras irene                                       2
dlf the crest                                     2
vatika inxt floors                                2
m3m latitude                                      2
the close south                                   2
shyam apartment                                   2
shree shyam residency                             2
sahara grace                                      2
pioneer urban presidia                            2
apartment                                         2
elan the presidential                             2
ansal heights                                     2
raheja atlantis                                   2
bptp freedom park life                            2
vipul world floors                                2
lagoon apartment                                  2
milan cghs 9                                      2
element one service                               2
ramprastha city                                   2
breeze global heights                             2
shapoorji pallonji joyville                       2
housing board colony                              2
nbcc heights                                      2
mahindra luminare                                 2
suncity heights                                   2
dlf city                                          2
landmark the residency                            2
puri the aravallis                                2
vasant appartments                                2
maruti vihar                                      2
silverglades hightown residences                  2
m3m urbana                                        2
m3m ikonic                                        2
green campus chs                                  2
om appartments                                    2
ambience caitriona                                2
supertech hill town                               2
mrg world ultimus                                 2
raheja vanya                                      2
suncity avenue 76                                 2
bptp pedestal                                     2
ansal api esencia                                 2
bestech spa signature                             2
awho shanti vihar                                 2
central park 2 bellevue                           2
palam vihar society                               2
today callidora                                   2
godrej nature plus serenity                       2
rof aalayas                                       2
lavanya apartments                                2
cghs airport apartment                            2
ansal api celebrity suites                        2
espire south                                      1
dnha group housing society                        1
the castle society                                1
raheja the vedaanta floors                        1
bptp park generations                             1
whiteland the aspen                               1
malibu towers                                     1
surbhi apartment                                  1
emaar the palm drive                              1
bsf chs                                           1
new colony, gurgaon                               1
park view apartments                              1
antriksh green                                    1
supertech new soft launch                         1
cghs hewo apartments                              1
511 sarahah tower                                 1
ansal height 86                                   1
kibithu villas                                    1
ansal plaza                                       1
raheja vedas                                      1
kamal residence                                   1
belgravia resort residences                       1
tulip yellow                                      1
ashray apartment                                  1
g l s arawali homes                               1
krishna appartment                                1
adarsh nagar                                      1
ansal sushant residency                           1
divya apartments                                  1
shreeram apartment ii                             1
ild grand centra                                  1
vidya apartment                                   1
proxima tower                                     1
palam vihar extension west zone rwa               1
maruti kunj                                       1
city shri ram apartments 1                        1
nan                                               1
ansals highland park                              1
shree balaji appartment                           1

In [126]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# **PRICE COLUMN :**

In [127]:
df['price'].head()

0        45 Lac
1        50 Lac
2        40 Lac
3    1.47 Crore
4        70 Lac
Name: price, dtype: object

In [128]:
df['price'].shape

(3028,)

In [129]:
df = df.dropna(subset=['price']) # Drop rows where 'price' is NaN

In [130]:
df['price'].shape

(3008,)

In [132]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
1.32 Crore          13
82 Lac              13
78 Lac              13
38 Lac              13
3.25 Crore          13
2.7 Crore           13
92 Lac              13
42 Lac              12
5 Crore             12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
32 Lac              11
Price on Request    11
88 Lac              11
1.08 Crore          11
25 Lac              11
26 Lac              10
1.78 Crore          10
87 Lac              10
1.12 Crore          10
28 Lac              10
1.28 Crore          10
2.55 Crore          10
2.05 Crore           9
36 Lac               9
2.85 Crore           9
3.45 Crore           9
1.72 Crore           9
99 Lac               9
22 Lac               9
4 Crore              9
1.68 Crore           9
27 Lac               8
1.54 Crore           8
3.2 Crore            8
98 Lac               8
1.76 Crore           8
6 Crore              8
86 Lac               8
56 Lac               8
6.5 Crore            8
48 Lac               8
4.25 Crore           8
2.75 Crore           8
1.18 Crore           8
20 Lac               8
1.26 Crore           8
97 Lac               7
3.3 Crore            7
3.7 Crore            7
72 Lac               7
1.27 Crore           7
1.19 Crore           7
1.36 Crore           7
2.9 Crore            7
1.02 Crore           7
46 Lac               7
39 Lac               7
1.99 Crore           7
1.29 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.01 Crore           6
1.49 Crore           6
1.98 Crore           6
3.9 Crore            6
3.65 Crore           6
37 Lac               6
5.5 Crore            6
1.07 Crore           6
21 Lac               6
2.95 Crore           6
96 Lac               6
1.16 Crore           6
1.13 Crore           6
1.34 Crore           6
54 Lac               6
3.35 Crore           6
1.51 Crore           6
1.14 Crore           6
3.05 Crore           6
4.1 Crore            6
1.39 Crore           6
71.5 Lac             6
1.17 Crore           5
1.92 Crore           5
3.75 Crore           5
2.22 Crore           5
6.75 Crore           5
1.44 Crore           5
1.24 Crore           5
1.69 Crore           5
1.82 Crore           5
49 Lac               5
1.33 Crore           5
2.78 Crore           5
1.91 Crore           5
1.43 Crore           5
66 Lac               5
1.83 Crore           5
1.47 Crore           5
29 Lac               5
4.5 Crore            5
2.12 Crore           5
2.29 Crore           5
93 Lac               5
1.62 Crore           5
68 Lac               5
64 Lac               5
1.79 Crore           5
1.93 Crore           5
24 Lac               5
41.5 Lac             4
5.6 Crore            4
1.52 Crore           4
1.23 Crore           4
1.22 Crore           4
4.3 Crore            4
28.5 Lac             4
2.09 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
67 Lac               4
58 Lac               4
1.37 Crore           4
74 Lac               4
1.31 Crore           4
1.58 Crore           4
6.15 Crore           4
3.95 Crore           4
3.6 Crore            4
1.77 Crore           4
5.9 Crore            4
7 Crore              4
73 Lac               4
89 Lac               4
1.48 Crore           4
1.71 Crore           4
33 Lac               4
31 Lac               4
4.85 Crore           4
1.64 Crore           4
1.66 Crore           4
36.5 Lac             4
3.1 Crore            4
52 Lac               3
2.01 Crore           3
51 Lac               3
2.08 Crore           3
1.41 Crore           3
83 Lac               3
94 Lac               3
2.24 Crore           3
3.49 Crore           3
2.51 Crore           3
1.67 Crore           3
47 Lac               3
1.21 Crore           3
4.8 Crore            3
4.75 Crore           3
2.36 Crore           3
72.5 Lac             3
1.04 Crore           3
64.5 Lac             3
2.79 Crore           3
2.33 Crore           3
1.88 Crore           3
5.8 Crore            3
3.85 Crore           3
91 Lac               3
1.09 Crore           3
1.63 Crore           3
2.03 Crore           3
4.2 Crore            3
3.15 Crore           3
34 Lac               3
1.57 Crore           3
3.8 Crore            3
69 Lac               3
2.28 Crore           3
84 Lac               3
8 Crore              2
2.23 Crore           2
53 Lac               2
2.17 Crore           2
27.1 Lac             2
77.5 Lac             2
8.5 Crore            2
2.14 Crore           2
6.2 Crore            2
2.52 Crore           2
53.5 Lac             2
2.58 Crore           2
4.49 Crore           2
1.46 Crore           2
4.26 Crore           2
2.57 Crore           2
2.99 Crore           2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
2.41 Crore           2
5.2 Crore            2
2.02 Crore           2
14 Crore             2
2.87 Crore           2
2.26 Crore           2
56.2 Lac             2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.13 Crore           2
4.55 Crore           2
2.04 Crore           2
25.5 Lac             2
27.75 Lac            2
4.45 Crore           2
11 Crore             2
4.7 Crore            2
7.5 Crore            2
88.5 Lac             2
37.1 Lac             1
54.8 Lac             1
63.4 Lac             1
2.38 Crore           1
2.64 Crore           1
3.98 Crore           1
4.02 Crore           1
7.4 Crore            1
97.5 Lac             1
39.5 Lac             1
2.06 Crore           1
2.07 Crore           1
64.45 Lac            1
44 Lac               1
2.49 Crore           1
3.78 Crore           1
2.92 Crore           1
9 Crore              1
61 Lac               1
4.21 Crore           1
89.77 Lac            1
4.16 Crore           1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
68.85 Lac            1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
1.97 Crore           1
82.5 Lac             1
13.2 Crore           1
98.88 Lac            1
3.99 Crore           1
37.5 Lac             1
2.32 Crore           1
2.44 Crore           1
57 Lac               1
1.74 Crore           1
95.5 Lac             1
94.5 Lac             1
2.96 Crore           1
29.8 Lac             1
6.02 Crore           1
96.07 Lac            1
7.9 Crore            1
32.5 Lac             1
3.23 Crore           1
19 Lac               1
70.85 Lac            1
97.04 Lac            1
40.3 Lac             1
3.72 Crore           1
88.4 Lac             1
94.99 Lac            1
1.53 Crore           1
7.52 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
2.69 Crore           1
86.99 Lac            1
9.95 Crore           1
86.92 Lac            1
9.2 Crore            1
49.5 Lac             1
2.54 Crore           1
16 Lac               1
7.8 Crore            1
2.86 Crore           1
15 Crore             1
4.4 Crore            1
9.3 Crore            1
5.3 Crore            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
2.72 Crore           1
98.1 Lac             1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
55.6 Lac             1
2.63 Crore           1
5.15 Crore           1
47.5 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
2.77 Crore           1
55.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
9.14 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
62.5 Lac             1
Name: count, dtype: int64

In [133]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [134]:
df = df[df['price'] != 'Price on Request']

In [135]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [136]:
def treat_price(x):
    if isinstance(x, float): # Check if x is already a float
        return x
    else:
        try: # Handle potential IndexError
            x = x.split()
            if len(x) > 1 and x[1] == 'Lac':
                return round(float(x[0])/100,2)
            elif len(x) > 0:  # Check if x has at least one element
                return round(float(x[0]),2)
            else:
                return np.nan # Or handle empty price as needed
        except (ValueError, TypeError): # Handle non-numeric price
            return np.nan # Or handle invalid price as needed

In [137]:
df['price'] = df['price'].apply(treat_price)

In [138]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

## price_per_sqft

In [139]:
df['price_per_sqft'].shape

(2997,)

In [140]:
df['price_per_sqft'].head()

0     ₹ 5,000/sq.ft.
1     ₹ 7,692/sq.ft.
2     ₹ 6,722/sq.ft.
3    ₹ 12,250/sq.ft.
4     ₹ 5,204/sq.ft.
Name: price_per_sqft, dtype: object

In [141]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 5,000/sq.ft.      13
₹ 6,666/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 9,230/sq.ft.       6
₹ 11,111/sq.ft.      6
₹ 8,928/sq.ft.       6
₹ 6,578/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 4,666/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 8,571/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,142/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,888/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 5,384/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 8,043/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 13,750/sq.ft.      4
₹ 16,666/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 13,636/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 8,163/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 4,854/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 6,404/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 5,878/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 8,886/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 9,615/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 5,856/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 8,450/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 8,078/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 7,948/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 6,421/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,500/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 9,011/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 9,473/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 13,392/sq.ft.      3
₹ 8,215/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 6,839/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 16,747/sq.ft.      2
₹ 12,012/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 4,761/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 16,608/sq.ft.      2
₹ 9,672/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 7,945/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 8,600/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 6,353/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 8,324/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 14,285/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 6,987/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 6,465/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 6,406/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 6,141/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 4,080/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 7,490/sq.ft.       2
₹ 13,709/sq.ft.      2
₹ 6,076/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 7,850/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 10,651/sq.ft.      2
₹ 9,433/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 6,243/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 10,545/sq.ft.      2
₹ 5,564/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 8,424/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,950/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 9,791/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 10,489/sq.ft.      2
₹ 9,589/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 9,139/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 8,294/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 6,029/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 9,025/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 8,518/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 8,670/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 7,987/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,100/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 5,150/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 6,647/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 6,455/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 7,223/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 9,128/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,506/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 10,531/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,200/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 10,666/sq.ft.      2
₹ 6,967/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 7,200/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 9,333/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 7,225/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 9,851/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 9,259/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 5,641/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,812/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 8,053/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 9,449/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 6,024/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 8,972/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 10,018/sq.ft.      2
₹ 9,600/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 4,820/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 5,284/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 7,857/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 8,075/sq.ft.       2
₹ 7,248/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 9,677/sq.ft.       2
₹ 6,134/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 6,927/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 14,583/sq.ft.      2
₹ 10,476/sq.ft.      2
₹ 8,720/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 7,796/sq.ft.       2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 6,190/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 6,206/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 58/sq.ft.          2
₹ 8,036/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 11,516/sq.ft.      2
₹ 12,777/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,755/sq.ft.      2
₹ 12,782/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 6,593/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 6,554/sq.ft.       1
₹ 14,358/sq.ft.      1
₹ 9,370/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 9,380/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 4,106/sq.ft.       1
₹ 14,658/sq.ft.      1
₹ 6,485/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 14,632/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 10,754/sq.ft.      1
₹ 6,194/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 15,560/sq.ft.      1
₹ 3,664/sq.ft.       1
₹ 3,650/sq.ft.       1
₹ 22,346/sq.ft.      1
₹ 20,666/sq.ft.      1
₹ 11,209/sq.ft.      1
₹ 22,222/sq.ft.      1
₹ 5,296/sq.ft.       1
₹ 9/sq.ft.           1
₹ 9,002/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 4,108/sq.ft.       1
₹ 15,262/sq.ft.      1
₹ 3,713/sq.ft.       1
₹ 10,309/sq.ft.      1
₹ 6,033/sq.ft.       1
₹ 5,813/sq.ft.       1
₹ 4,886/sq.ft.       1
₹ 12,272/sq.ft.      1
₹ 10,306/sq.ft.      1
₹ 18,688/sq.ft.      1
₹ 7,679/sq.ft.       1
₹ 9,696/sq.ft.       1
₹ 8,558/sq.ft.       1
₹ 5,739/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 8,124/sq.ft.       1
₹ 7,931/sq.ft.       1
₹ 11,074/sq.ft.      1
₹ 9,264/sq.ft.       1
₹ 14,680/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 7,917/sq.ft.       1
₹ 10,483/sq.ft.      1
₹ 11,094/sq.ft.      1
₹ 20,707/sq.ft.      1
₹ 6,272/sq.ft.       1
₹ 8,349/sq.ft.       1
₹ 10,888/sq.ft.      1
₹ 10,452/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,031/sq.ft.      1
₹ 10,408/sq.ft.      1
₹ 14,783/sq.ft.      1
₹ 10,101/sq.ft.      1
₹ 10,172/sq.ft.      1
₹ 5,621/sq.ft.       1
₹ 18,392/sq.ft.      1
₹ 7,006/sq.ft.       1
₹ 12,791/sq.ft.      1
₹ 9,236/sq.ft.       1
₹ 8,494/sq.ft.       1
₹ 9,687/sq.ft.       1
₹ 14,603/sq.ft.      1
₹ 4,545/sq.ft.       1
₹ 6,319/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 10,924/sq.ft.      1
₹ 4,219/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 12,420/sq.ft.      1
₹ 8,026/sq.ft.       1
₹ 14,379/sq.ft.      1
₹ 12,489/sq.ft.      1
₹ 8,953/sq.ft.       1
₹ 9,714/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 13,425/sq.ft.      1
₹ 8,674/sq.ft.       1
₹ 4,941/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 6,751/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 9,130/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 591/sq.ft.         1
₹ 3,671/sq.ft.       1
₹ 6,881/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 23,344/sq.ft.      1
₹ 7,066/sq.ft.       1
₹ 5,904/sq.ft.       1
₹ 7,227/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 13,522/sq.ft.      1
₹ 5,329/sq.ft.       1
₹ 6,176/sq.ft.       1
₹ 7,561/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 9,076/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 7,164/sq.ft.       1
₹ 9,219/sq.ft.       1
₹ 4,971/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 11,559/sq.ft.      1
₹ 10,094/sq.ft.      1
₹ 4,375/sq.ft.       1
₹ 7,988/sq.ft.       1
₹ 4,729/sq.ft.       1
₹ 11,854/sq.ft.      1
₹ 13,936/sq.ft.      1
₹ 11,178/sq.ft.      1
₹ 7,293/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 14,838/sq.ft.      1
₹ 9,519/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 9,513/sq.ft.       1
₹ 8,554/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 7,654/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 5,041/sq.ft.       1
₹ 15,901/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 4,587/sq.ft.       1
₹ 5,590/sq.ft.       1
₹ 13,480/sq.ft.      1
₹ 10,071/sq.ft.      1
₹ 5,910/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 8,737/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,120/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 6,951/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 14,267/sq.ft.      1
₹ 9,569/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 9,252/sq.ft.       1
₹ 4,927/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 6,905/sq.ft.       1
₹ 6,346/sq.ft.       1
₹ 4,821/sq.ft.       1
₹ 9,583/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 11,989/sq.ft.      1
₹ 11,190/sq.ft.      1
₹ 8,446/sq.ft.       1
₹ 6,998/sq.ft.       1
₹ 8,111/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 7,760/sq.ft.       1
₹ 8,907/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 6,083/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 7,547/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 5,443/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 8,840/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 5,479/sq.ft.       1
₹ 7,714/sq.ft.       1
₹ 5,931/sq.ft.       1
₹ 4,931/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 9,125/sq.ft.       1
₹ 4,923/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 6,979/sq.ft.       1
₹ 11,386/sq.ft.      1
₹ 11,423/sq.ft.      1
₹ 6,159/sq.ft.       1
₹ 15,360/sq.ft.      1
₹ 9,734/sq.ft.       1
₹ 8,052/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 4,404/sq.ft.       1
₹ 13,984/sq.ft.      1
₹ 6,587/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 6,556/sq.ft.       1
₹ 7,262/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 15,982/sq.ft.      1
₹ 7,010/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 6,137/sq.ft.       1
₹ 11,725/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 10,418/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 7,171/sq.ft.       1
₹ 10,697/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 11,525/sq.ft.      1
₹ 5,720/sq.ft.       1
₹ 11,497/sq.ft.      1
₹ 5,958/sq.ft.       1
₹ 8,700/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 7,402/sq.ft.       1
₹ 8,387/sq.ft.       1
₹ 7,453/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 8,802/sq.ft.       1
₹ 6,435/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 8,404/sq.ft.       1
₹ 10,903/sq.ft.      1
₹ 13,177/sq.ft.      1
₹ 9,459/sq.ft.       1
₹ 19,943/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 13,989/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 10,815/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 6,502/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 17,729/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 8,264/sq.ft.       1
₹ 9,701/sq.ft.       1
₹ 17,691/sq.ft.      1
₹ 9,102/sq.ft.       1
₹ 4,637/sq.ft.       1
₹ 8,347/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 10,375/sq.ft.      1
₹ 9,016/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 6,870/sq.ft.       1
₹ 11,741/sq.ft.      1
₹ 10,163/sq.ft.      1
₹ 11,920/sq.ft.      1
₹ 6,552/sq.ft.       1
₹ 5,265/sq.ft.       1
₹ 8,240/sq.ft.       1
₹ 7,891/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 9,218/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 6,022/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 6,914/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 8,522/sq.ft.       1
₹ 6,601/sq.ft.       1
₹ 9,745/sq.ft.       1
₹ 17,615/sq.ft.      1
₹ 4,478/sq.ft.       1
₹ 5,719/sq.ft.       1
₹ 7,604/sq.ft.       1
₹ 12,912/sq.ft.      1
₹ 13,126/sq.ft.      1
₹ 4,512/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 4,694/sq.ft.       1
₹ 6,598/sq.ft.       1
₹ 4,591/sq.ft.       1
₹ 14,652/sq.ft.      1
₹ 3,692/sq.ft.       1
₹ 6,185/sq.ft.       1
₹ 5,220/sq.ft.       1
₹ 13,608/sq.ft.      1
₹ 14,009/sq.ft.      1
₹ 5,039/sq.ft.       1
₹ 4,325/sq.ft.       1
₹ 5,013/sq.ft.       1
₹ 19,444/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 4,453/sq.ft.       1
₹ 7,422/sq.ft.       1
₹ 8,515/sq.ft.       1
₹ 3,600/sq.ft.       1
₹ 4,977/sq.ft.       1
₹ 9,879/sq.ft.       1
₹ 4,250/sq.ft.       1
₹ 7,389/sq.ft.       1
₹ 4,716/sq.ft.       1
₹ 5,933/sq.ft.       1
₹ 15,178/sq.ft.      1
₹ 13,975/sq.ft.      1
₹ 7,754/sq.ft.       1
₹ 5,261/sq.ft.       1
₹ 8,990/sq.ft.       1
₹ 14,754/sq.ft.      1
₹ 12,408/sq.ft.      1
₹ 4,470/sq.ft.       1
₹ 14,551/sq.ft.      1
₹ 6,526/sq.ft.       1
₹ 15,267/sq.ft.      1

In [142]:
df['price_per_sqft'].str.contains('area').value_counts()

price_per_sqft
False    2996
True        1
Name: count, dtype: int64

In [171]:
df = df[~df['price_per_sqft'].str.contains('area')]

In [174]:
df['price_per_sqft']=df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',', '').str.strip().astype(float)

In [175]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# **BEDROOM**

In [146]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     943
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [147]:
df['bedRoom'].str.split(' ').str.get(0).astype(int)

0       2
1       2
2       2
3       2
4       2
5       2
6       3
7       3
8       2
9       3
10      2
11      2
12      3
13      2
14      2
15      4
16      1
17      2
19      3
20      2
21      3
22      2
23      3
24      3
26      2
27      3
28      3
29      2
30      2
31      2
32      4
33      2
34      3
35      2
36      2
37      3
38      2
39      2
40      3
41      2
42      3
43      4
44      2
45      3
46      4
47      2
48      3
49      3
50      3
51      2
52      2
53      3
54      2
55      4
56      1
57      1
58      3
59      2
60      2
61      2
62      4
63      2
64      3
65      4
66      3
67      3
68      2
69      2
70      2
71      3
72      2
73      2
74      2
75      3
76      2
77      2
78      3
79      3
80      3
81      3
82      2
83      5
84      2
85      2
86      3
87      3
88      2
89      2
90      2
91      2
92      3
93      3
94      3
95      2
96      4
97      3
98      2
99      3
100     3
101     3
102     3
103     2
104     1
105     3
106     3
107     2
108     2
109     1
110     2
111     2
112     1
113     2
114     2
115     2
116     3
117     3
118     4
119     3
120     3
121     2
122     2
123     3
124     3
125     3
126     3
127     2
128     2
129     2
130     4
131     1
132     3
133     2
134     2
135     3
136     3
137     2
138     2
139     2
140     3
141     3
142     4
143     4
144     3
145     3
146     2
147     3
148     3
149     2
150     3
151     2
152     3
153     3
154     2
155     4
156     2
157     3
158     3
159     2
160     3
161     3
162     3
163     2
164     2
165     3
166     4
167     1
168     2
169     2
170     3
171     2
172     2
173     4
174     3
175     4
176     4
177     4
178     2
179     3
180     3
181     3
182     3
183     1
184     2
185     4
186     3
187     3
188     1
189     2
190     2
191     3
192     3
193     4
194     2
195     3
196     2
197     2
198     2
199     2
200     2
201     2
202     3
203     4
204     3
205     2
206     2
207     2
208     2
209     2
210     2
211     3
212     2
213     2
214     3
215     2
216     2
217     3
218     3
219     5
220     3
221     2
222     3
223     4
224     2
225     2
226     2
227     3
228     2
229     2
230     2
231     3
232     2
233     2
234     3
235     3
236     2
237     3
238     3
239     2
240     2
241     3
242     2
243     3
244     3
245     3
246     3
247     2
248     2
249     2
250     3
251     2
252     2
253     2
254     2
255     3
256     4
257     3
258     3
259     4
260     2
261     4
262     3
263     3
264     4
265     2
266     2
267     3
268     3
269     2
270     2
271     3
272     3
273     2
274     2
275     2
276     2
277     2
278     3
279     1
280     3
281     3
282     3
283     1
284     4
285     3
287     4
288     3
289     3
290     3
291     3
292     4
293     3
294     2
295     3
296     2
297     2
298     3
299     3
300     2
301     4
302     2
303     3
304     1
305     5
306     4
307     3
308     3
309     3
310     3
311     3
312     3
313     2
314     4
315     3
316     4
317     4
318     2
319     3
320     3
321     3
322     3
323     3
324     3
325     2
326     3
327     2
328     4
329     2
330     3
331     1
332     5
333     4
334     3
335     3
336     3
337     2
338     3
339     4
340     2
341     3
342     4
343     2
344     3
345     3
346     4
347     3
348     3
349     2
350     3
351     3
352     2
353     1
354     2
355     4
356     2
357     2
358     3
359     2
360     3
361     3
362     3
363     3
364     3
365     3
366     3
367     4
368     2
369     3
370     3
371     4
372     3
373     2
374     3
375     3
376     3
377     4
378     3
379     3
380     4
381     3
382     4
383     4
384     4
385     4
386     3
387     3
388     4
389     3
390     3
391     3
392     3
393     2
394     4
395     3
396     3
397     2
398     3
399     2
400     4
401     3
402     3
403     2
404     3
405     3
406     3
407     4
408     3
409     3
410     3
411     3
412     3
413     4
414     3
415     5
416     4
417     3
418     3
419     2
420     3
421     3
422     4
423     4
424     3
425     3
426     3
427     5
428     3
429     4
430     4
431     3
432     3
433     3
434     3
435     3
436     4
437     3
438     3
439     3
440     3
441     4
442     3
443     3
444     4
445     3
446     4
447     4
448     3
449     4
450     3
451     3
452     3
453     3
454     4
455     4
456     2
457     4
458     3
459     3
460     3
461     3
462     3
463     3
464     3
465     4
466     3
467     3
468     4
469     3
470     2
471     3
472     2
473     4
474     3
475     2
476     3
477     3
478     3
479     3
480     3
481     3
482     3
483     3
484     3
485     2
486     2
487     2
488     3
489     3
490     3
491     2
492     3
493     2
494     3
495     3
496     1
497     4
498     3
499     3
500     3
501     3
502     4
503     3
504     2
505     5
506     4
507     3
508     4
509     3
510     5
511     3
512     3
513     2
514     3
515     3
516     3
517     3
518     3
519     3
520     3
521     3
522     3
523     2
524     4
525     3
526     3
527     2
528     1
529     4
530     3
531     3
532     2
533     2
534     3
535     3
536     3
537     4
538     4
539     4
540     2
541     4
542     2
543     4
544     2
545     3
546     2
547     4
548     4
549     4
550     3
551     2
552     3
553     3
554     3
555     3
556     3
557     4
558     3
559     3
560     3
561     3
562     2
563     3
564     3
565     4
566     3
567     3
568     3
569     3
570     4
571     4
572     4
573     3
574     3
575     2
576     3
577     2
578     2
579     3
580     4
581     3
582     3
583     3
584     3
585     3
586     3
587     4
588     3
589     4
590     2
591     4
592     2
593     3
594     3
595     4
596     3
597     4
598     3
599     4
600     3
601     3
602     3
603     2
604     3
605     3
606     3
607     3
608     3
609     3
610     3
611     3
612     3
613     3
614     3
615     4
616     4
617     4
618     2
619     4
620     3
621     3
622     3
623     2
624     3
625     3
626     2
627     2
628     3
629     2
630     3
631     2
632     3
633     2
634     3
635     3
636     4
637     2
638     3
639     3
640     3
641     3
642     3
643     3
644     3
645     2
646     5
647     3
648     4
649     4
650     3
651     3
652     3
653     3
654     4
655     4
656     4
657     3
658     2
659     3
660     3
661     3
662     3
663     5
664     3
665     2
666     3
667     1
668     3
669     4
670     3
671     3
672     3
673     2
674     5
675     4
676     3
677     4
678     3
679     4
680     3
681     3
682     3
683     2
684     3
685     4
686     4
687     3
688     3
689     4
690     3
691     4
692     3
693     3
694     3
695     2
696     2
697     3
698     4
699     3
700     3
701     3
702     3
703     2
704     3
705     3
706     3
707     3
708     3
709     4
710     4
711     3
712     4
713     4
714     4
715     4
716     2
717     3
718     3
719     4
720     2
721     3
722     3
723     2
724     2
725     2
726     2
727     3
728     3
729     2
730     2
731     3
732     4
733     2
734     3
735     2
736     3
737     3
738     2
739     2
740     3
741     2
742     3
743     3
744     3
745     3
746     3
747     3
748     3
749     3
750     3
751     2
752     3
753     3
754     3
755     3
756     3
757     3
758     4
759     3
760     3
761     3
762     3
763     3
764     3
765     3
766     4
767     3
768     3
769     3
770     4
771     3
772     3
773     4
774     2
775     3
776     2
777     3
778     4
779     4
780     3
781     4
782     3
783     3
784     3
785     3
786     3
787     4
788     3
789     2
790     3
791     2
792     4
793     3
794     2
795     2
796     3
797     4
798     3
799     4
800     3
801     3
802     3
803     2
804     3
805     3
806     2
807     2
808     3
809     2
810     3
811     5
812     3
813     2
814     3
815     3
816     2
817     3
818     3
819     3
820     4
821     3
822     3
823     3
824     4
825     3
826     3
827     3
828     4
829     3
830     4
831     3
832     3
833     3
834     3
835     3
836     3
837     2
838     4
839     3
840     3
841     3
842     3
843     3
844     3
845     5
846     3
847     2
848     3
849     4
850     4
851     4
852     4
853     3
854     4
855     3
856     3
857     3
858     3
859     3
860     3
861     3
862     4
863     3
864     3
865     3
866     3
867     3
868     4
869     2
870     1
871     2
872     3
873     3
874     3
875     2
876     2
877     3
878     3
879     3
880     3
881     2
882     4
883     3
884     3
885     3
886     3
887     4
888     3
889     3
890     4
891     3
892     3
893     4
894     3
895     4
896     2
897     3
898     4
899     3
900     2
901     3
902     3
903     2
904     3
905     2
906     3
907     4
908     4
909     3
910     2
911     3
912     3
913     4
914     2
915     3
916     3
917     3
918     2
919     2
920     4
921     2
922     3
923     3
924     3
925     2
926     4
927     3
928     2
929     2
930     3
931     3
932     2
933     2
934     2
935     4
936     3
937     3
938     3
939     3
940     3
941     2
942     3
943     4
944     3
945     1
946     3
947     2
948     3
949     3
950     2
951     4
952     4
953     3
954     4
955     2
956     3
957     3
958     3
959     2
960     2
961     3
962     4
963     3
964     4
965     3
966     3
967     3
968     3
969     2
970     2
971     3
972     4
973     4
974     3
975     4
976     3
977     3
978     3
979     3
980     3
981     3
982     3
983     3
984     3
985     4
986     2
987     2
988     2
989     2
990     3
991     3
992     3
993     3
994     3
995     3
996     3
997     3
998     3
999     3
1000    5
1001    3
1002    3
1003    3
1004    3
1005    2
1006    2
1007    2
1008    2
1009    4
1010    3
1011    2
1012    4
1013    3
1014    3
1015    3
1016    3
1017    2
1018    3
1019    3
1020    4
1021    2
1022    4
1023    4
1024    4
1025    4
1026    3
1027    4
1028    2
1029    3
1030    3
1031    3
1032    4
1033    2
1034    2
1035    3
1036    3
1037    3
1038    3
1039    4
1040    4
1041    4
1042    3
1043    3
1044    4
1045    3
1046    4
1047    3
1048    3
1049    4
1050    3
1051    2
1052    3
1053    4
1054    3
1055    3
1056    3
1057    3
1058    3
1059    2
1060    2
1061    4
1062    3
1063    3
1064    3
1065    2
1066    4
1067    3
1068    3
1069    4
1070    3
1071    4
1072    3
1073    4
1074    2
1075    4
1076    3
1077    3
1078    3
1079    3
1080    2
1081    4
1082    3
1083    3
1084    4
1085    4
1086    3
1087    3
1088    3
1089    1
1090    3
1091    3
1092    3
1093    3
1094    3
1095    4
1096    4
1097    3
1098    2
1099    2
1100    3
1101    4
1102    4
1103    2
1104    3
1105    2
1106    2
1107    3
1108    3
1109    2
1110    2
1111    2
1112    2
1113    3
1114    3
1115    2
1116    3
1117    4
1118    2
1119    3
1120    4
1121    4
1122    3
1123    3
1124    3
1125    3
1126    2
1127    4
1128    3
1129    3
1130    2
1131    3
1132    2
1133    4
1134    4
1135    3
1136    4
1137    4
1138    3
1139    3
1140    3
1141    3
1142    3
1143    3
1144    3
1145    4
1146    3
1147    3
1148    3
1149    2
1150    4
1151    2
1152    3
1153    3
1154    3
1155    3
1156    2
1157    2
1158    2
1159    2
1160    1
1161    2
1162    3
1163    2
1164    2
1165    2
1166    3
1167    4
1168    3
1169    4
1170    4
1171    3
1172    4
1173    2
1174    4
1175    4
1176    4
1177    3
1178    3
1179    2
1180    3
1181    3
1182    3
1183    3
1184    2
1185    3
1186    2
1187    3
1188    3
1189    2
1190    3
1191    3
1192    4
1193    2
1194    3
1195    4
1196    3
1197    4
1198    2
1199    5
1200    4
1201    4
1202    3
1203    3
1204    2
1205    3
1206    3
1207    3
1208    1
1209    2
1210    2
1211    1
1212    2
1213    3
1214    4
1215    3
1216    2
1217    3
1218    2
1219    4
1220    3
1221    4
1222    2
1223    2
1224    2
1225    3
1226    2
1227    2
1228    3
1229    2
1230    3
1231    2
1232    3
1233    2
1234    3
1235    4
1236    3
1237    4
1238    3
1239    3
1240    3
1241    3
1242    3
1243    3
1244    3
1245    3
1246    3
1247    4
1248    3
1249    2
1250    3
1251    2
1252    4
1253    3
1254    4
1255    3
1256    3
1257    4
1258    2
1259    2
1260    2
1261    2
1262    2
1263    2
1264    2
1265    3
1266    3
1267    3
1268    4
1269    3
1270    2
1271    2
1272    3
1273    3
1274    3
1275    2
1276    3
1277    3
1278    3
1279    3
1280    3
1281    3
1282    3
1283    2
1284    3
1285    3
1286    4
1287    4
1288    3
1289    3
1290    2
1291    3
1292    3
1293    3
1294    3
1295    3
1296    3
1297    3
1298    3
1299    3
1300    3
1301    4
1302    3
1303    3
1304    3
1305    3
1306    3
1307    2
1308    1
1309    2
1310    2
1311    3
1312    1
1313    1
1314    3
1315    2
1316    3
1317    4
1318    4
1319    3
1320    4
1321    4
1322    4
1323    3
1324    3
1325    2
1326    4
1327    2
1328    3
1329    3
1330    3
1331    3
1332    2
1333    2
1334    1
1335    1
1336    3
1337    3
1338    2
1339    4
1340    4
1341    3
1342    4
1343    2
1344    4
1345    2
1346    3
1347    2
1348    3
1349    3
1350    3
1351    1
1352    3
1353    3
1354    3
1355    3
1356    3
1357    3
1358    3
1359    4
1360    2
1361    3
1362    3
1363    3
1364    3
1365    4
1366    2
1367    4
1368    3
1369    4
1370    3
1371    3
1372    4
1373    3
1374    3
1375    3
1376    3
1377    4
1378    3
1379    2
1380    3
1381    3
1382    3
1383    3
1384    3
1385    4
1386    4
1387    3
1388    3
1389    2
1390    3
1391    3
1392    2
1393    3
1394    3
1395    2
1396    3
1397    3
1398    3
1399    2
1400    3
1401    3
1402    2
1403    4
1404    3
1405    3
1406    3
1407    2
1408    2
1409    4
1410    3
1411    3
1412    3
1413    4
1414    2
1415    2
1416    4
1417    3
1418    4
1419    2
1420    4
1421    4
1422    2
1423    2
1424    3
1425    3
1426    3
1427    4
1428    4
1429    3
1430    3
1431    3
1432    3
1433    1
1434    2
1435    2
1436    2
1437    3
1438    3
1439    3
1440    2
1441    2
1442    3
1443    2
1444    3
1445    3
1446    3
1447    2
1448    2
1449    2
1450    2
1451    2
1452    2
1453    3
1454    2
1455    4
1456    4
1457    4
1458    3
1459    4
1460    3
1461    3
1462    3
1463    3
1464    3
1465    2
1466    2
1467    3
1468    3
1469    4
1470    3
1471    3
1472    5
1473    4
1474    4
1475    3
1476    4
1477    3
1478    4
1479    3
1480    2
1481    2
1482    2
1483    2
1484    2
1485    3
1486    3
1487    4
1488    3
1489    3
1490    3
1491    3
1492    3
1493    3
1494    3
1495    4
1496    3
1497    3
1498    3
1499    2
1500    3
1501    3
1502    3
1503    3
1504    4
1505    3
1506    3
1507    3
1508    4
1509    4
1510    3
1511    3
1512    3
1513    2
1514    3
1515    3
1516    2
1517    3
1518    3
1519    3
1520    4
1521    3
1522    4
1523    4
1524    2
1525    2
1526    2
1527    4
1528    4
1529    4
1530    4
1531    3
1532    2
1533    2
1534    2
1535    2
1536    3
1537    3
1538    3
1539    5
1540    5
1541    5
1542    2
1543    2
1544    4
1545    4
1546    2
1547    4
1548    2
1549    2
1550    3
1551    3
1552    3
1553    4
1554    3
1555    4
1556    3
1557    2
1558    3
1559    2
1560    2
1561    4
1562    3
1563    3
1564    2
1565    2
1566    2
1567    2
1568    2
1569    2
1570    2
1571    3
1572    3
1573    4
1574    4
1575    2
1576    3
1577    2
1578    3
1579    2
1580    3
1581    3
1582    2
1583    3
1584    4
1585    3
1586    3
1587    3
1588    2
1589    2
1590    3
1591    2
1592    4
1593    3
1594    3
1595    3
1596    2
1597    3
1598    2
1599    2
1600    3
1601    4
1602    3
1603    3
1604    2
1605    1
1606    3
1607    2
1608    2
1609    4
1610    4
1611    3
1612    3
1613    3
1614    3
1615    3
1616    3
1617    3
1618    3
1619    3
1620    3
1621    3
1622    3
1623    3
1624    4
1625    3
1626    4
1627    3
1628    4
1629    3
1630    4
1631    3
1632    3
1633    3
1634    4
1635    4
1636    4
1637    4
1638    4
1639    4
1640    3
1641    4
1642    4
1643    3
1644    3
1646    4
1647    3
1648    3
1649    2
1650    3
1651    3
1652    2
1653    2
1654    3
1655    3
1656    2
1657    3
1658    3
1659    3
1660    4
1661    3
1662    4
1663    4
1664    3
1665    3
1666    3
1667    2
1668    4
1669    3
1670    3
1671    3
1672    4
1673    3
1674    4
1675    3
1676    3
1677    3
1678    4
1679    4
1680    3
1681    3
1682    3
1683    3
1684    2
1685    3
1686    3
1687    1
1688    3
1689    2
1690    4
1691    4
1692    3
1693    3
1694    3
1695    4
1696    3
1697    2
1698    3
1699    2
1700    3
1701    3
1702    4
1703    3
1704    3
1705    3
1706    3
1707    3
1708    3
1709    4
1710    4
1711    2
1712    3
1713    3
1714    3
1715    3
1716    4
1717    3
1718    3
1719    2
1720    2
1721    3
1722    3
1723    3
1724    3
1725    4
1726    3
1727    3
1728    3
1729    2
1730    3
1731    3
1732    3
1733    2
1734    3
1735    2
1736    4
1737    3
1738    3
1739    2
1740    4
1741    2
1742    3
1743    3
1744    4
1745    3
1746    2
1747    4
1748    4
1749    3
1750    3
1751    3
1752    3
1753    4
1754    3
1755    3
1756    4
1757    3
1758    3
1759    3
1760    3
1761    3
1762    3
1763    4
1764    4
1765    4
1766    3
1767    3
1768    4
1769    3
1770    3
1771    4
1772    3
1773    3
1774    3
1775    3
1776    3
1777    3
1778    3
1779    2
1780    2
1781    2
1782    2
1783    3
1784    3
1785    3
1786    2
1787    3
1788    3
1789    4
1790    3
1791    2
1792    3
1793    3
1794    4
1795    3
1796    4
1797    4
1798    3
1799    4
1800    4
1801    3
1802    3
1803    2
1804    2
1805    3
1806    3
1807    3
1808    3
1809    3
1810    3
1811    3
1812    3
1813    3
1814    3
1815    2
1816    2
1817    3
1818    2
1819    3
1820    3
1821    4
1822    3
1823    3
1824    3
1825    3
1826    2
1827    4
1828    3
1829    2
1830    3
1831    3
1832    3
1833    3
1834    3
1835    2
1836    3
1837    3
1838    3
1839    3
1840    3
1841    2
1842    2
1843    2
1844    3
1845    3
1846    3
1847    3
1848    4
1849    2
1850    3
1851    2
1852    2
1853    3
1854    3
1855    3
1856    4
1857    4
1858    3
1859    3
1860    4
1861    3
1862    3
1863    3
1864    3
1865    4
1866    3
1867    2
1868    4
1869    3
1870    2
1871    3
1872    3
1873    3
1874    3
1875    2
1876    2
1877    4
1878    3
1879    2
1880    3
1881    3
1882    4
1883    4
1884    3
1885    3
1886    3
1887    3
1888    3
1889    3
1890    2
1891    2
1892    2
1893    3
1894    3
1895    2
1896    2
1897    3
1898    4
1899    3
1900    3
1901    3
1902    3
1903    2
1904    3
1905    3
1906    2
1907    2
1908    2
1909    2
1910    2
1911    3
1912    2
1913    1
1914    3
1915    4
1916    2
1917    1
1918    1
1919    1
1920    3
1921    1
1922    2
1923    3
1924    3
1925    3
1926    4
1927    2
1928    2
1929    2
1930    3
1931    3
1932    3
1933    4
1934    3
1935    5
1936    2
1937    2
1938    3
1939    3
1940    4
1941    2
1942    3
1943    2
1944    3
1945    3
1946    2
1947    3
1948    2
1949    2
1950    4
1951    2
1952    3
1953    3
1954    3
1955    4
1956    3
1957    3
1958    2
1959    3
1960    3
1961    3
1962    2
1963    5
1964    2
1965    2
1966    3
1967    3
1968    3
1969    3
1970    3
1971    2
1972    2
1974    2
1975    4
1976    3
1977    3
1978    3
1979    3
1980    3
1981    3
1982    2
1983    3
1984    2
1985    3
1986    2
1987    3
1988    4
1989    2
1990    2
1991    2
1992    2
1993    2
1994    2
1995    4
1996    4
1997    3
1998    2
1999    3
2000    3
2001    2
2002    3
2003    3
2004    3

In [148]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [149]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [150]:
df['bathroom'].isnull().value_counts()

bathroom
False    2996
Name: count, dtype: int64

In [151]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)

In [152]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [153]:
df['balcony'].value_counts()

balcony
3 Balconies     973
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [154]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [155]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [156]:
# additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [157]:
df['additionalRoom'].value_counts().shape

(49,)

In [158]:
df['additionalRoom'].isnull().sum()

1304

In [159]:
df['additionalRoom'].fillna('not available',inplace=True)

<ipython-input-159-37c81a970354>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [160]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [161]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# **Floor Num**

In [162]:
df['floorNum'].head()

0      4th   of 4 Floors
1      1st   of 3 Floors
2    12nd   of 14 Floors
3      2nd   of 4 Floors
4      5th   of 8 Floors
Name: floorNum, dtype: object

In [163]:

df['floorNum'].isnull().sum()

2

In [164]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).str.replace('Basement','-1').str.replace('Lower','0').replace('Ground','0').str.extract(r'(\d+)')

In [165]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

# FACING **COLUMN**

In [166]:
df['facing'].isnull().sum()

874

In [167]:
df['facing'].fillna('NA',inplace=True)

<ipython-input-167-e6ba103970bd>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [168]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [176]:

df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [177]:
df.insert(loc=1,column='property_type',value='flat')

In [178]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   property_type    2996 non-null   object
 2   society          2996 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2996 non-null   object
 7   bedRoom          2996 non-null   int64
 8   bathroom         2996 non-null   int64
 9   balcony          2996 non-null   object
 10  additionalRoom   2996 non-null   object
 11  address          2990 non-null   object
 12  floorNum         2994 non-null   object
 13  facing           2996 non-null   object
 14  agePossession    2995 non-null   object
 15  nearbyLocations  2905 non-null   object
 16  description      2996 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2589 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.5+ KB

In [180]:
df.shape

(2996, 20)

In [181]:
df.to_csv('flats_cleaned.csv',index=False)